services:
  - type: web
    name: 91proxy
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
